///////////////////////////////////////////////////////////////////////////
//
//    Copyright 2010
//
//    This file is part of rootpwa
//
//    rootpwa is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    rootpwa is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with rootpwa.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////
//-------------------------------------------------------------------------
// File and Version Information:
// $Rev:: 644                         $: revision of last commit
// $Author:: sschmeing                $: author of last commit
// $Date:: 2011-02-28 18:50:36 +0100 #$: date of last commit
//
// Description:
//      Header file for the FortranPwaFilePhaseSpaceIntegrals class that provides
//		functionality to read in phase space integrals from
//		txt files generated by fortran pwa and store them
//
//
// Author List:
//      Stephan Schmeing          TUM            (original author)
//
//
//-------------------------------------------------------------------------

#ifndef FortranPwaFilePhaseSpaceIntegrals_H
#define FortranPwaFilePhaseSpaceIntegrals_H

#include <iostream>
#include <fstream>
#include <string>
#include <map>

#include "FortranPwaFileBase.h"

class FortranPwaFilePhaseSpaceIntegrals : public FortranPwaFileBase {
private:
	// Variables
	std::map<const std::string,const double> _PhaseSpaceIntegralsMap; ///< Map of phase space integrals sorted by their wave names

	// Functions

public:
	// Constructors + Destructors
	FortranPwaFilePhaseSpaceIntegrals( void ); ///< Constructor

	// Get && Set

	// Functions
	int ReadFromFile( std::basic_istream<char>& File ); ///< Reads the rest of the information from a phase space integral file and returns 0 if no error occurred or a negative number as the error code
	void Print( void ) const; ///< Prints all important variables of class
};

#endif /* FortranPwaFilePhaseSpaceIntegrals_H */
