///////////////////////////////////////////////////////////////////////////
//
//    Copyright 2009 Sebastian Neubert
//
//    This file is part of rootpwa
//
//    rootpwa is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    rootpwa is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with rootpwa.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////
//-----------------------------------------------------------
//
// Description:
//      Loads basic libraries and functions needed for analyzing fit
//      results
//
//
// Author List:
//      Sebastian Neubert    TUM            (original author)
//
//
//-----------------------------------------------------------


{
	// set include paths
	gSystem->AddIncludePath("-I$ROOTPWA/amplitude");
	gSystem->AddIncludePath("-I$ROOTPWA/tools");
	gSystem->AddIncludePath("-I$ROOTPWA/generators");
	gSystem->AddIncludePath("-I$ROOTPWA/src");
	gSystem->AddIncludePath("-I$ROOTPWA/utilities");
	gSystem->AddIncludePath("-I$BOOST_ROOT");
	gSystem->AddIncludePath("-I$LIBCONFIG/include");

	// define macro ROOT_CINT; used to exclude code parts from ACLiC compilation
	gSystem->AddIncludePath("-DROOT_CINT");

	// switch off shadowing warnings
	//gDebug = 7;	// print command lines generated by ACLiC
	TString cmd = gSystem->GetMakeSharedLib();
	cmd.ReplaceAll("-Wshadow", "-Wno-shadow");
	gSystem->SetMakeSharedLib(cmd.Data());

	// load shared libraries
	gSystem->Load("libGX11TTF.so");
	gSystem->Load("libRootPwa.so");
	gSystem->Load("libRootPwaAmp.so");
	gSystem->Load("libRootPwaTools.so");
	gSystem->Load("libRootPwaGen.so");
}
