//
// File generated by rootcint at Fri Dec  3 10:50:48 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rpwaDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TrpwaWaveSelectFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TrpwaWaveSelectFrame(void *p);
   static void deleteArray_TrpwaWaveSelectFrame(void *p);
   static void destruct_TrpwaWaveSelectFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TrpwaWaveSelectFrame*)
   {
      ::TrpwaWaveSelectFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TrpwaWaveSelectFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TrpwaWaveSelectFrame", ::TrpwaWaveSelectFrame::Class_Version(), "../src/TrpwaWaveSelectFrame.h", 27,
                  typeid(::TrpwaWaveSelectFrame), DefineBehavior(ptr, ptr),
                  &::TrpwaWaveSelectFrame::Dictionary, isa_proxy, 0,
                  sizeof(::TrpwaWaveSelectFrame) );
      instance.SetDelete(&delete_TrpwaWaveSelectFrame);
      instance.SetDeleteArray(&deleteArray_TrpwaWaveSelectFrame);
      instance.SetDestructor(&destruct_TrpwaWaveSelectFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TrpwaWaveSelectFrame*)
   {
      return GenerateInitInstanceLocal((::TrpwaWaveSelectFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TrpwaWaveSelectFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TrpwaMainFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TrpwaMainFrame*)
   {
      ::TrpwaMainFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TrpwaMainFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TrpwaMainFrame", ::TrpwaMainFrame::Class_Version(), "../src/TrpwaMainFrame.h", 31,
                  typeid(::TrpwaMainFrame), DefineBehavior(ptr, ptr),
                  &::TrpwaMainFrame::Dictionary, isa_proxy, 0,
                  sizeof(::TrpwaMainFrame) );
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TrpwaMainFrame*)
   {
      return GenerateInitInstanceLocal((::TrpwaMainFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TrpwaMainFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TrpwaWaveSelectFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TrpwaWaveSelectFrame::Class_Name()
{
   return "TrpwaWaveSelectFrame";
}

//______________________________________________________________________________
const char *TrpwaWaveSelectFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TrpwaWaveSelectFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TrpwaWaveSelectFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TrpwaWaveSelectFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TrpwaWaveSelectFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TrpwaWaveSelectFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TrpwaWaveSelectFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TrpwaWaveSelectFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TrpwaMainFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TrpwaMainFrame::Class_Name()
{
   return "TrpwaMainFrame";
}

//______________________________________________________________________________
const char *TrpwaMainFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TrpwaMainFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TrpwaMainFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TrpwaMainFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TrpwaMainFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TrpwaMainFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TrpwaMainFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TrpwaMainFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TrpwaMainFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class TrpwaMainFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void TrpwaMainFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TrpwaMainFrame.
      TClass *R__cl = ::TrpwaMainFrame::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fEcanvas", &fEcanvas);
      R__insp.Inspect(R__cl, R__parent, "*steplist", &steplist);
      R__insp.Inspect(R__cl, R__parent, "*frame_session_options", &frame_session_options);
      R__insp.Inspect(R__cl, R__parent, "progressbars", (void*)&progressbars);
      ::ROOT::GenericShowMembers("vector<TGProgressBar*>", (void*)&progressbars, R__insp, strcat(R__parent,"progressbars."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "stepbuttons", (void*)&stepbuttons);
      ::ROOT::GenericShowMembers("vector<TGTextButton*>", (void*)&stepbuttons, R__insp, strcat(R__parent,"stepbuttons."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*current_session", &current_session);
      R__insp.Inspect(R__cl, R__parent, "*frame_wave_select", &frame_wave_select);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
} // end of namespace ROOT for class ::TrpwaMainFrame

//______________________________________________________________________________
void TrpwaWaveSelectFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class TrpwaWaveSelectFrame.

   TGTransientFrame::Streamer(R__b);
}

//______________________________________________________________________________
void TrpwaWaveSelectFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TrpwaWaveSelectFrame.
      TClass *R__cl = ::TrpwaWaveSelectFrame::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*_waveselections", &_waveselections);
      R__insp.Inspect(R__cl, R__parent, "_selected_bin", &_selected_bin);
      R__insp.Inspect(R__cl, R__parent, "*_button_allbins", &_button_allbins);
      R__insp.Inspect(R__cl, R__parent, "*_copybinbutton", &_copybinbutton);
      R__insp.Inspect(R__cl, R__parent, "_buttons_binselection", (void*)&_buttons_binselection);
      ::ROOT::GenericShowMembers("vector<TGTextButton*>", (void*)&_buttons_binselection, R__insp, strcat(R__parent,"_buttons_binselection."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "_buttons_waveselection", (void*)&_buttons_waveselection);
      ::ROOT::GenericShowMembers("vector<TGTextButton*>", (void*)&_buttons_waveselection, R__insp, strcat(R__parent,"_buttons_waveselection."),false);
      R__parent[R__ncp] = 0;
      TGTransientFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TrpwaWaveSelectFrame(void *p) {
      delete ((::TrpwaWaveSelectFrame*)p);
   }
   static void deleteArray_TrpwaWaveSelectFrame(void *p) {
      delete [] ((::TrpwaWaveSelectFrame*)p);
   }
   static void destruct_TrpwaWaveSelectFrame(void *p) {
      typedef ::TrpwaWaveSelectFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TrpwaWaveSelectFrame

/********************************************************
* ../src/rpwaDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablerpwaDict();

extern "C" void G__set_cpp_environmentrpwaDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("../src/TrpwaMainFrame.h");
  G__add_compiledheader("../src/TrpwaWaveSelectFrame.h");
  G__cpp_reset_tagtablerpwaDict();
}
#include <new>
extern "C" int G__cpp_dllrevrpwaDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TrpwaWaveSelectFrame */
static int G__rpwaDict_621_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TrpwaWaveSelectFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TrpwaWaveSelectFrame(*(TWaveSelections*) libp->para[0].ref);
   } else {
     p = new((void*) gvp) TrpwaWaveSelectFrame(*(TWaveSelections*) libp->para[0].ref);
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaWaveSelectFrame*) G__getstructoffset())->Build();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaWaveSelectFrame*) G__getstructoffset())->BinSelectClick();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaWaveSelectFrame*) G__getstructoffset())->WaveSelectClick();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TrpwaWaveSelectFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrpwaWaveSelectFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TrpwaWaveSelectFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TrpwaWaveSelectFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaWaveSelectFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrpwaWaveSelectFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrpwaWaveSelectFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrpwaWaveSelectFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_621_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrpwaWaveSelectFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TrpwaWaveSelectFrame G__TTrpwaWaveSelectFrame;
static int G__rpwaDict_621_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TrpwaWaveSelectFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TrpwaWaveSelectFrame*) (soff+(sizeof(TrpwaWaveSelectFrame)*i)))->~G__TTrpwaWaveSelectFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TrpwaWaveSelectFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TrpwaWaveSelectFrame*) (soff))->~G__TTrpwaWaveSelectFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TrpwaMainFrame */
static int G__rpwaDict_626_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TrpwaMainFrame& obj = TrpwaMainFrame::Instance();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->CheckStatus();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->NewSession();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->SaveSession();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->SaveSessionAs();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->LoadSession();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->Update();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->SelectWaves();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->FitPartialWaves();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->ShowFitResults();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->GenKeys();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->CalcAmps();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->IntAmps();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->FilterData();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->SetupWorkspace();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->FillFlatPhaseSpaceEvents();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->Dummy();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TrpwaMainFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrpwaMainFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TrpwaMainFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TrpwaMainFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TrpwaMainFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrpwaMainFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrpwaMainFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TrpwaMainFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rpwaDict_626_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TrpwaMainFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TrpwaWaveSelectFrame */

/* TrpwaMainFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrpwaDict {
 public:
  G__Sizep2memfuncrpwaDict(): p(&G__Sizep2memfuncrpwaDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrpwaDict::*p)();
};

size_t G__get_sizep2memfuncrpwaDict()
{
  G__Sizep2memfuncrpwaDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerpwaDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame))) {
     TrpwaWaveSelectFrame *G__Lderived;
     G__Lderived=(TrpwaWaveSelectFrame*)0x1000;
     {
       TGTransientFrame *G__Lpbase=(TGTransientFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGTransientFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),G__get_linked_tagnum(&G__rpwaDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame))) {
     TrpwaMainFrame *G__Lderived;
     G__Lderived=(TrpwaMainFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),G__get_linked_tagnum(&G__rpwaDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerpwaDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TrpwaBinInfo>",117,G__get_linked_tagnum(&G__rpwaDictLN_maplEintcOTrpwaBinInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOTrpwaBinInfogRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TrpwaBinInfo,less<int> >",117,G__get_linked_tagnum(&G__rpwaDictLN_maplEintcOTrpwaBinInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOTrpwaBinInfogRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<string> >",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<string,allocator<string> > >",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string> >",117,G__get_linked_tagnum(&G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> > >",117,G__get_linked_tagnum(&G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,vector<string,allocator<string> >,less<string> >",117,G__get_linked_tagnum(&G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TWaveSelection>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TWaveSelections",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGTextButton*>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TGProgressBar*>",117,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rpwaDictLN_reverse_iteratorlEvectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TrpwaWaveSelectFrame */
static void G__setup_memvarTrpwaWaveSelectFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame));
   { TrpwaWaveSelectFrame *p; p=(TrpwaWaveSelectFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR),G__defined_typename("TWaveSelections"),-1,4,"_waveselections=",0,"set and selected waves");
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"_selected_bin=",0,"-1 if all bins");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TGButton),-1,-1,4,"_button_allbins=",0,"reference to button with all bins");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TGButton),-1,-1,4,"_copybinbutton=",0,"reference to button to copy bins");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR),G__defined_typename("vector<TGTextButton*>"),-1,4,"_buttons_binselection=",0,"holds the buttons to all bins");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR),G__defined_typename("vector<TGTextButton*>"),-1,4,"_buttons_waveselection=",0,"holds the buttons to all waves");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TrpwaMainFrame */
static void G__setup_memvarTrpwaMainFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame));
   { TrpwaMainFrame *p; p=(TrpwaMainFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),-1,-2,4,"pInstance=",0,"singleton reference");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TGVerticalFrame),-1,-1,4,"steplist=",0,"frame holding frames for each step");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TGGroupFrame),-1,-1,4,"frame_session_options=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR),G__defined_typename("vector<TGProgressBar*>"),-1,4,"progressbars=",0,"references to the progress bars");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR),G__defined_typename("vector<TGTextButton*>"),-1,4,"stepbuttons=",0,"references to the buttons calling the step procedures");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TrpwaSessionManager),-1,-1,4,"current_session=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),-1,-1,4,"frame_wave_select=",0,"window for wave selection");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rpwaDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrpwaDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTrpwaWaveSelectFrame(void) {
   /* TrpwaWaveSelectFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame));
   G__memfunc_setup("UpdateWaveButtons",1765,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CopyWaveSelection",1748,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i - - 0 - frombin i - - 0 - tobin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TrpwaWaveSelectFrame",2028,G__rpwaDict_621_0_3, 105, G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame), -1, 0, 1, 1, 1, 0, "u 'vector<TWaveSelection,allocator<TWaveSelection> >' 'TWaveSelections' 1 - waveselections", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Build",496,G__rpwaDict_621_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BinSelectClick",1375,G__rpwaDict_621_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WaveSelectClick",1497,G__rpwaDict_621_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rpwaDict_621_0_7, 85, G__get_linked_tagnum(&G__rpwaDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TrpwaWaveSelectFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rpwaDict_621_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrpwaWaveSelectFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rpwaDict_621_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TrpwaWaveSelectFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rpwaDict_621_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TrpwaWaveSelectFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rpwaDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rpwaDict_621_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rpwaDict_621_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrpwaWaveSelectFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rpwaDict_621_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TrpwaWaveSelectFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rpwaDict_621_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrpwaWaveSelectFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rpwaDict_621_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TrpwaWaveSelectFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TrpwaWaveSelectFrame", 2154, G__rpwaDict_621_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTrpwaMainFrame(void) {
   /* TrpwaMainFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame));
   G__memfunc_setup("TrpwaMainFrame",1406,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame), -1, 0, 3, 1, 4, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Build",496,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Instance",821,G__rpwaDict_626_0_3, 117, G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame), -1, 1, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TrpwaMainFrame& (*)())(&TrpwaMainFrame::Instance) ), 0);
   G__memfunc_setup("CheckStatus",1122,G__rpwaDict_626_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NewSession",1038,G__rpwaDict_626_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveSession",1139,G__rpwaDict_626_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SaveSessionAs",1319,G__rpwaDict_626_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadSession",1124,G__rpwaDict_626_0_8, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Update",611,G__rpwaDict_626_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", "override to call the application abortion", (void*) NULL, 1);
   G__memfunc_setup("SelectWaves",1126,G__rpwaDict_626_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", "calls the interface for wave selection", (void*) NULL, 0);
   G__memfunc_setup("FitPartialWaves",1526,G__rpwaDict_626_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", "send jobs for partial wave fitting", (void*) NULL, 0);
   G__memfunc_setup("ShowFitResults",1462,G__rpwaDict_626_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", "send a command to show the available fit results", (void*) NULL, 0);
   G__memfunc_setup("GenKeys",694,G__rpwaDict_626_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", "send a command to generate the key files", (void*) NULL, 0);
   G__memfunc_setup("CalcAmps",772,G__rpwaDict_626_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", "send jobs to calculate amplitudes", (void*) NULL, 0);
   G__memfunc_setup("IntAmps",700,G__rpwaDict_626_0_16, 121, -1, -1, 0, 0, 1, 1, 0, "", "send jobs to integrate available amplitudes", (void*) NULL, 0);
   G__memfunc_setup("FilterData",992,G__rpwaDict_626_0_17, 121, -1, -1, 0, 0, 1, 1, 0, "", "filter data given by root files", (void*) NULL, 0);
   G__memfunc_setup("SetupWorkspace",1472,G__rpwaDict_626_0_18, 121, -1, -1, 0, 0, 1, 1, 0, "", "Setup workspace as specified in the init file", (void*) NULL, 0);
   G__memfunc_setup("FillFlatPhaseSpaceEvents",2400,G__rpwaDict_626_0_19, 121, -1, -1, 0, 0, 1, 1, 0, "", "calling flat phase space generator bin by bin", (void*) NULL, 0);
   G__memfunc_setup("Dummy",524,G__rpwaDict_626_0_20, 121, -1, -1, 0, 0, 1, 1, 0, "", "will be called for every function not implemented yet", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rpwaDict_626_0_21, 85, G__get_linked_tagnum(&G__rpwaDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TrpwaMainFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rpwaDict_626_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrpwaMainFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rpwaDict_626_0_23, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TrpwaMainFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rpwaDict_626_0_24, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TrpwaMainFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rpwaDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rpwaDict_626_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rpwaDict_626_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrpwaMainFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rpwaDict_626_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TrpwaMainFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rpwaDict_626_0_31, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TrpwaMainFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rpwaDict_626_0_32, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TrpwaMainFrame::DeclFileLine) ), 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrpwaDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrpwaDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrpwaDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rpwaDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__rpwaDictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGTransientFrame = { "TGTransientFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_maplEintcOTrpwaBinInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOTrpwaBinInfogRsPgRsPgR = { "map<int,TrpwaBinInfo,less<int>,allocator<pair<const int,TrpwaBinInfo> > >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TrpwaSessionManager = { "TrpwaSessionManager" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR = { "vector<vector<string,allocator<string> >,allocator<vector<string,allocator<string> > > >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<string,allocator<string> >,allocator<vector<string,allocator<string> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR = { "map<string,vector<string,allocator<string> >,less<string>,allocator<pair<const string,vector<string,allocator<string> > > > >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TGButton = { "TGButton" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR = { "vector<TWaveSelection,allocator<TWaveSelection> >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TWaveSelection,allocator<TWaveSelection> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TrpwaWaveSelectFrame = { "TrpwaWaveSelectFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR = { "vector<TGTextButton*,allocator<TGTextButton*> >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGTextButton*,allocator<TGTextButton*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_TrpwaMainFrame = { "TrpwaMainFrame" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR = { "vector<TGProgressBar*,allocator<TGProgressBar*> >" , 99 , -1 };
G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TGProgressBar*,allocator<TGProgressBar*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerpwaDict() {
  G__rpwaDictLN_TClass.tagnum = -1 ;
  G__rpwaDictLN_TBuffer.tagnum = -1 ;
  G__rpwaDictLN_TMemberInspector.tagnum = -1 ;
  G__rpwaDictLN_TObject.tagnum = -1 ;
  G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rpwaDictLN_TGObject.tagnum = -1 ;
  G__rpwaDictLN_TQObject.tagnum = -1 ;
  G__rpwaDictLN_TGWindow.tagnum = -1 ;
  G__rpwaDictLN_TGFrame.tagnum = -1 ;
  G__rpwaDictLN_TGCompositeFrame.tagnum = -1 ;
  G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__rpwaDictLN_TGVerticalFrame.tagnum = -1 ;
  G__rpwaDictLN_TGMainFrame.tagnum = -1 ;
  G__rpwaDictLN_TGTransientFrame.tagnum = -1 ;
  G__rpwaDictLN_TGGroupFrame.tagnum = -1 ;
  G__rpwaDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rpwaDictLN_maplEintcOTrpwaBinInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOTrpwaBinInfogRsPgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_TrpwaSessionManager.tagnum = -1 ;
  G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_TGButton.tagnum = -1 ;
  G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rpwaDictLN_TrpwaWaveSelectFrame.tagnum = -1 ;
  G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rpwaDictLN_TrpwaMainFrame.tagnum = -1 ;
  G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR.tagnum = -1 ;
  G__rpwaDictLN_reverse_iteratorlEvectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerpwaDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGTransientFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGGroupFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_maplEintcOTrpwaBinInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOTrpwaBinInfogRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TrpwaSessionManager);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_TGButton);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaWaveSelectFrame),sizeof(TrpwaWaveSelectFrame),-1,62464,(char*)NULL,G__setup_memvarTrpwaWaveSelectFrame,G__setup_memfuncTrpwaWaveSelectFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__rpwaDictLN_TrpwaMainFrame),sizeof(TrpwaMainFrame),-1,62464,(char*)NULL,G__setup_memvarTrpwaMainFrame,G__setup_memfuncTrpwaMainFrame);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rpwaDictLN_reverse_iteratorlEvectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setuprpwaDict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprpwaDict()");
  G__set_cpp_environmentrpwaDict();
  G__cpp_setup_tagtablerpwaDict();

  G__cpp_setup_inheritancerpwaDict();

  G__cpp_setup_typetablerpwaDict();

  G__cpp_setup_memvarrpwaDict();

  G__cpp_setup_memfuncrpwaDict();
  G__cpp_setup_globalrpwaDict();
  G__cpp_setup_funcrpwaDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrpwaDict();
  return;
}
class G__cpp_setup_initrpwaDict {
  public:
    G__cpp_setup_initrpwaDict() { G__add_setup_func("rpwaDict",(G__incsetup)(&G__cpp_setuprpwaDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrpwaDict() { G__remove_setup_func("rpwaDict"); }
};
G__cpp_setup_initrpwaDict G__cpp_setup_initializerrpwaDict;

