/********************************************************************
* ../src/rpwaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ../src/rpwaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablerpwaDict();
extern void G__cpp_setup_inheritancerpwaDict();
extern void G__cpp_setup_typetablerpwaDict();
extern void G__cpp_setup_memvarrpwaDict();
extern void G__cpp_setup_globalrpwaDict();
extern void G__cpp_setup_memfuncrpwaDict();
extern void G__cpp_setup_funcrpwaDict();
extern void G__set_cpp_environmentrpwaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../src/TrpwaMainFrame.h"
#include "../src/TrpwaPlotAmpsFrame.h"
#include "../src/TrpwaWaveSelectFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rpwaDictLN_TClass;
extern G__linked_taginfo G__rpwaDictLN_TBuffer;
extern G__linked_taginfo G__rpwaDictLN_TMemberInspector;
extern G__linked_taginfo G__rpwaDictLN_TObject;
extern G__linked_taginfo G__rpwaDictLN_string;
extern G__linked_taginfo G__rpwaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rpwaDictLN_TGObject;
extern G__linked_taginfo G__rpwaDictLN_TQObject;
extern G__linked_taginfo G__rpwaDictLN_TGWindow;
extern G__linked_taginfo G__rpwaDictLN_TGFrame;
extern G__linked_taginfo G__rpwaDictLN_TGCompositeFrame;
extern G__linked_taginfo G__rpwaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rpwaDictLN_TGTextButton;
extern G__linked_taginfo G__rpwaDictLN_TGVerticalFrame;
extern G__linked_taginfo G__rpwaDictLN_TGMainFrame;
extern G__linked_taginfo G__rpwaDictLN_TGTransientFrame;
extern G__linked_taginfo G__rpwaDictLN_TGGroupFrame;
extern G__linked_taginfo G__rpwaDictLN_TCanvas;
extern G__linked_taginfo G__rpwaDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__rpwaDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rpwaDictLN_maplEintcOTrpwaBinInfocOlesslEintgRcOallocatorlEpairlEconstsPintcOTrpwaBinInfogRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_TrpwaSessionManager;
extern G__linked_taginfo G__rpwaDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rpwaDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rpwaDictLN_maplEstringcOvectorlEstringcOallocatorlEstringgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_TGButton;
extern G__linked_taginfo G__rpwaDictLN_TGComboBox;
extern G__linked_taginfo G__rpwaDictLN_vectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlETWaveSelectioncOallocatorlETWaveSelectiongRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rpwaDictLN_TrpwaWaveSelectFrame;
extern G__linked_taginfo G__rpwaDictLN_vectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rpwaDictLN_maplEintcOvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_maplEstringcOvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlETGTextButtonmUcOallocatorlETGTextButtonmUgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_maplEstringcOTTreemUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTTreemUgRsPgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_TrpwaPlotAmpsFrame;
extern G__linked_taginfo G__rpwaDictLN_TrpwaMainFrame;
extern G__linked_taginfo G__rpwaDictLN_vectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgR;
extern G__linked_taginfo G__rpwaDictLN_reverse_iteratorlEvectorlETGProgressBarmUcOallocatorlETGProgressBarmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
