#!/bin/bash
# Select queue
#$ -l medium=TRUE,h_vmem=100M
# Divert output
#$ -o /nfs/hicran/project/compass/analysis/sneubert/LOGS/
# Write error in same file
#$ -j y

# this script requires KEY to be set to the keydirectory!
# and BIN to be set to the mass bin directory

export WORK=/nfs/nas/user/sneubert/
export DIARYFILE=$WORK/scratch/COMPASS/rootpwa/trunk/scripts/bindiary.txt

export MAXKEYPERJOB=1;

export SET=F21565SET
export KEY=$WORK/scratch/COMPASS/rootpwa/trunk/keyfiles/key5pi/$SET
export PDG=$WORK/scratch/COMPASS/rootpwa/trunk/keyfiles/key5pi/pdgTable.txt
echo "---- STARTING AMPLITUDE CALCULATIONS";
echo "---- WAVESET: $KEY";
echo;

test -s $KEY || exit
ls $KEY

#export DATADIR=/nfs/data/user/sneubert/5PiData2
cd $WORK/scratch/COMPASS/rootpwa/trunk
source setup.sh
cd scripts/

# find bin
TEMPLIST=`mktemp -t dirlist.XXXXXX`
#ROOTDIR=/afs/e18/compass/analysis/sneubert/5PiData
#ROOTDIR=/nfs/hicran/project/compass/analysis/sneubert/5PiLTData3
ROOTDIR=/nfs/nas/user/sneubert/2004/5PiLTData3/
#ROOTDIR=/afs/e18/compass/analysis/sneubert/5PiMTData
#ROOTDIR=/afs/e18/compass/analysis/sneubert/2008/5PiBins
#ROOTDIR=/afs/e18/compass/analysis/sneubert/5PiModels/ImpTest/pieces3
#ROOTDIR=/lustre/e18/user/sneubert/2008/5PiBins
#ROOTDIR=/lustre/e18/user/sneubert/5PiMC/ACC_HT
echo ROOTDIR=$ROOTDIR
ls $ROOTDIR
ls $ROOTDIR > $TEMPLIST

echo SGE_TASK_ID=$SGE_TASK_ID

MYBIN=`./SetWorkdir.sh $TEMPLIST $SGE_TASK_ID`

echo "Starting $SET for bin $MYBIN"
# logbook entries:
echo -e "Start: \c" >> $DIARYFILE
date >> $DIARYFILE
echo $ROOTDIR/$MYBIN >> $DIARYFILE
echo $SET >> $DIARYFILE
echo "--------------------------------" >> $DIARYFILE

export KEYDIR=$KEY
./buildBin.sh $ROOTDIR/$MYBIN



cd
